# Generated by Django 3.0.5 on 2020-07-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorType',
        ),
    ]
