# Generated by Django 3.0.5 on 2020-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_errortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('label', 'Wrong title or episode out of order'), ('video', 'Blurry, cut outs, look strange,...'), ('sound', 'Hard to hear, no match the video,...'), ('sub', 'Missing, hard to read, not match the sound,...'), ('connect', 'video wont start,...')], default=('video', 'Blurry, cut outs, look strange,...'), max_length=10, verbose_name='Problem type'),
        ),
    ]
